### ISSUE TITLE
connection from scratch outside of a browser

### ISSUE THREAD

**Issue by jmvanel** [read-write-web/rww-play#121]
It would be nice to have WebID + LDP clients not being a browser , but a local client written in Scala, Python or whatever.
For example, I would like to read and wrote the Web inside Stample using EulerGUI IDE
( http://svn.code.sf.net/p/eulergui/code/trunk/eulergui/html/documentation.html )

I think Henry has some curl or wget scripts to test connection outside of a browser;
this would help to commit them.

**Comment by sylvainlb** [comment]
Some examples here:
https://github.com/read-write-web/rww-play/wiki/Curl-Interactions

**Comment by bblfish** [comment]
yes, it does not require a browser. If there is a specific feature that is needed please let me know exactly.
