### ISSUE TITLE
Unable to test rww-play because of dead urls

### ISSUE THREAD

**Issue by glibersat** [read-write-web/rww-play#122]
Hi,

I've followed the README to try rww-play but can't get past the compile step because of this:

<pre>
[RWWeb] $ compile
[info] Updating {file:/home/glibersat/Source/rww/rww-play/}RWWeb...
[info] Resolving org.w3#banana-sesame_2.10;2013_10_07-SNAPSHOT ...
[error] Server access Error: Connexion terminée par expiration du délai d'attente url=http://repo.aduna-software.org/maven2/releases/org/w3/banana-sesame_2.10/2013_10_07-SNAPSHOT/maven-metadata.xml
[error] Server access Error: Connexion terminée par expiration du délai d'attente url=http://repo.aduna-software.org/maven2/releases/org/w3/banana-sesame_2.10/2013_10_07-SNAPSHOT/banana-sesame_2.10-2013_10_07-SNAPSHOT.pom
[error] Server access Error: Connexion terminée par expiration du délai d'attente url=http://repo.aduna-software.org/maven2/releases/org/w3/banana-sesame_2.10/2013_10_07-SNAPSHOT/banana-sesame_2.10-2013_10_07-SNAPSHOT.jar
[info] Resolving org.w3#banana-rdf_2.10;2013_10_07-SNAPSHOT ...
[error] Server access Error: Connexion terminée par expiration du délai d'attente url=http://repo.aduna-software.org/maven2/releases/org/w3/banana-rdf_2.10/2013_10_07-SNAPSHOT/maven-metadata.xml
[error] Server access Error: Connexion terminée par expiration du délai d'attente url=http://repo.aduna-software.org/maven2/releases/org/w3/banana-rdf_2.10/2013_10_07-SNAPSHOT/banana-rdf_2.10-2013_10_07-SNAPSHOT.pom
[error] Server access Error: Connexion terminée par expiration du délai d'attente url=http://repo.aduna-software.org/maven2/releases/org/w3/banana-rdf_2.10/2013_10_07-SNAPSHOT/banana-rdf_2.10-2013_10_07-SNAPSHOT.jar
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] Server access Error: Connexion terminée par expiration du délai d'attente url=http://repo.aduna-software.org/maven2/releases/org/sonatype/oss/oss-parent/7/oss-parent-7.jar
</pre>

Maybe the deps need to be updated?

Thx,

Guillaume

**Comment by bblfish** [comment]
I have reported the issue on the Sesame mailing list here:
https://groups.google.com/d/msg/sesame-users/06Q_gYvLup8/L-VbM4jzRRQJ

Hopefully this will get resolved quickly.

**Comment by bblfish** [comment]
@glibersat let me know if this now works for you. If it does please close this bug. Thanks.

**Comment by glibersat** [comment]
it now compiles, thanks :)
