### ISSUE TITLE
get rid of downloading custom play

### ISSUE THREAD

**Issue by antonkulaga** [read-write-web/rww-play#125]
Is there a reason of downloading custom build of play with more than 200 mbs?
As I undestand play is just an sbt plugin, so you can publish your TLS fork of play as sbt plugin in bintray and add it to plugins.sbt

**Comment by bblfish** [comment]
yes, that is needed because that custom build has TLS client certificate support which Play does not have and that is needed for http://webid.info/ .

**Comment by bblfish** [comment]
You can see how that is meant to work here: https://github.com/read-write-web/rww-play/wiki/Curl-Interactions

Not that I am about to release a version of Play 2.3.6 with TLS support, and switch the dev branch to master
