### ISSUE TITLE
dist packaging non fonctional

### ISSUE THREAD

**Issue by sylvainlb** [read-write-web/rww-play#138]
The dist command makes a package that doesn't run. It throws a ExceptionInInitializerError on startup.

**Comment by bblfish** [comment]
What is the dist command?

**Comment by jmvanel** [comment]
dist is a command of sbt that generates a zip for deployment on a server .

**Comment by sylvainlb** [comment]
In this case, it creates a zip package with a rwweb script in /bin/.
When running this script with the usual run parameters, it throws an ExceptionInInitializerError at play.api.GlobalSettings on the first request.

**Comment by sylvainlb** [comment]
On https request, it throws:

`Error while rendering default error page
scala.MatchError: java.lang.NoClassDefFoundError: Could not initialize class controllers.RdfSetup$ (of class java.lang.NoClassDefFoundError)
    at play.api.GlobalSettings`

**Comment by jmvanel** [comment]
This maybe a consequence of 
https://github.com/read-write-web/rww-play/issues/139

FYI I wrote here the normal procedure to run on a server:
https://github.com/jmvanel/semantic_forms/tree/master/scala/forms_play#run-on-a-server-without-development-environment

**Comment by sylvainlb** [comment]
I don't think so, because I did include the parameters, and apparently they were taken into account.
That's basically the procedure I followed.

**Comment by sylvainlb** [comment]
This was due to a missing target directory

**Comment by sylvainlb** [comment]
opened #146
