### ISSUE TITLE
ACLs should link to themselves as their own ACLs

### ISSUE THREAD

**Issue by bblfish** [read-write-web/rww-play#162]
See [issue 61: All resources MUST have at least one "acl" Link relation](https://github.com/solid/solid/issues/61) in solid/solid. 

```
GET /document.acl
...

200 Ok
Link: <>; rel="acl"

[] acl:accessTo <>;
   acl:mode acl:Write, acl:Read;
   acl:agent <card#me> .
```

Currently rww-play does not do this, but it makes a lot of sense, and should simplify the client side code.

**Comment by akuckartz** [comment]
How was this issue resolved?

**Comment by bblfish** [comment]
Thanks for the question. Somehow forgot to add the explanation here.

I have proved to my own satisfaction in [issue 61](https://github.com/solid/solid/issues/61#issuecomment-183633391) that the actual usage of acls with `wac:Control` is that they are their own acl, so that this is just making explicit what is implicit in accepted usage.

Then I discovered that rww-play already implements this. Probably just because it is a natural thing to do when you try to implement access control without `wac:Control` - see [issue 51: do we need wac:Control?](https://github.com/solid/solid/issues/51) - which we do.

But we can re-open this issue here if new relevant arguments come to bear.

**Comment by bblfish** [comment]
We have acls refer to acls  in rww-play since the November 2013 [commit 2198c642a4c214df8b19716f46a082085197f38d](https://github.com/read-write-web/rww-play/commit/2198c642a4c214df8b19716f46a082085197f38d).  I don't think I even mentioned this in the PR, as it must have seemed obvious when building it that this was a good idea.
