### ISSUE TITLE
modeling of Stample in RDF

### ISSUE THREAD

**Issue by bblfish** [read-write-web/rww-play#17]
Get a full model of Stamples in RDF.
Take a few examples of existing stamples with a use case and build a story from beginning to end.

**Comment by ColinMaudry** [comment]
So... where is the model? :-)

**Comment by bblfish** [comment]
Well Stample is a particular case. We are looking at more general cases at the W3C Social Web WG.
https://www.w3.org/wiki/Socialwg/Social_API/User_stories
