### ISSUE TITLE
finish create folder, file, etc in rww.io template

### ISSUE THREAD

**Issue by bblfish** [read-write-web/rww-play#23]
use the examples on the home page as inspiration here to make the ldp example in rdflib.js work.

**Comment by letnotimitateothers** [comment]
Now the creation of folder / file is working.
However, right I'm not using rdflib.js to do this.
Still looking how to use the library / other alternative libraries.
I just send a normal ajax POST with text/turtle string.

$.ajax({
        type: "POST",
        url: uri,
        dataType: "text",
        contentType:"text/turtle",
        processData:false,
        data: stringData,
        headers: {"Slug": name},
        success: function() {},
        error: function() {}
    })

The server respond with :+1: 
HTTP/1.1 201 Created
Location: https://localhost:8443/2013/newRepName/
Content-Length: 0
