### ISSUE TITLE
Run in play-2.2-TLS-7bbdcf599b80e1b1b9fa0aaaba4c6db1286eaf41/play

### ISSUE THREAD

**Issue by letnotimitateothers** [read-write-web/rww-play#25]
Doing "run" in play-2.2-TLS-7bbdcf599b80e1b1b9fa0aaaba4c6db1286eaf41/play 
I also get this : 

---

trace] Stack trace suppressed: run last *:update for the full output.
[error](*:update) sbt.ResolveException: unresolved dependency: org.w3#banana-sesame_2.10;2013_10_07-SNAPSHOT: not found
[error] unresolved dependency: org.w3#banana-jena_2.10;2013_10_07-SNAPSHOT: not found
[error] unresolved dependency: org.w3#banana-rdf_2.10;2013_10_07-SNAPSHOT: not found
[error] unresolved dependency: org.w3#plantain_2.10;2013_10_07-SNAPSHOT: not found

---

**Comment by bblfish** [comment]
fixed with commit bda8bfb296f7a50fc91cafd031789eb274d3ecc2
