### ISSUE TITLE
make server work for html view on RDF resource

### ISSUE THREAD

**Issue by bblfish** [read-write-web/rww-play#29]
This is the server side component of issue #20 .
The server needs to be adjusted for this.

**Comment by bblfish** [comment]
mostly done with commit 7a615a07df7b7e6f91007b7bece20504eaa56119
Sebastien tu peux faire en sorte que le fichier par defaut soit configurable de la conf play? Merci

**Comment by bblfish** [comment]
For explanation of the above patch see issue #20

**Comment by slorber** [comment]
tell me if it's good for you

**Comment by bblfish** [comment]
great. Thanks!
