### ISSUE TITLE
Inconsistant 401 error on some resources

### ISSUE THREAD

**Issue by slorber** [read-write-web/rww-play#34]
gggg is a LDPC that was created. On the test_www folder, we can see a gggg folder (empty)

When trying to access https://localhost:8443/2013/gggg/ in the browser, we get inconsistent responses. After many browser refresh, there is some kind of randomness between 2 cases:
- The access is not allowed 401
- The access is allowed and the answer is:

```
<> a <http://www.w3.org/ns/ldp#Container> ;
    <http://xmlns.com/foaf/0.1/topic> "A container for some type X of resources"^^<http://www.w3.org/2001/XMLSchema#string> ;
    <http://xmlns.com/foaf/0.1/maker> <https://localhost:8443/2013/card#me> .

<https://localhost:8443/2013/> <http://www.w3.org/ns/ldp#created> <> .
```

Notice that the Link rel=acl header also says that the acl file is /gggg/.acl while the file doesn't exist (gggg folder is empty)

This seems strange.
We had the same kind of behavior on a resource we created.

**Comment by slorber** [comment]
@bblfish , I can reproduce this bug by using curl and by using a browser user agent.

```
curl -i -k --cert eg/test-localhost.pem:test -A "Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3" https://localhost:8443/2013/card
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Content-Length: 32

no access for read on /2013/card
```

It works fine when not using that user agent.

**Comment by bblfish** [comment]
Ah oui, ca c'est parce que Mozilla peut retourner un certificate en mode WANT, mais pas curl qui ne le rend que en mode NEED. Comme le serveur determine le browseur et qu'il ajuste son comportement avec le browseur, si tu prétend etre mozilla mais que tu n'a pas les capacités de mozilla, ca ne va pas marcher.

**Comment by slorber** [comment]
J'ai le meme genre d'erreur en passant par le browser et par curl donc je suis pas certain que tu aies raison
La différence c'est qu'en mode browser l'erreur est une fois sur 2 alors que curl c'est tout le temps

**Comment by bblfish** [comment]
Ah donc il  y a une difference :-)

Il se trouve que des récentes versions de chromes sur le derniers OSX requierent le mode NEED. J'ai donc pris ca en compte dans un patch récent. Mais ca veux dire que pour l'instant tu peux utiliser ce user Agent pour avoir un browsur qui fonctionne de la même façon que curl. ( Le user Agent de Opera aurait aussi fonctionné). 

```
curl -I -k --cert ../eg/test-localhost.pem:test  -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.6 Safari/537.36" https://localhost:8443/2013/
HTTP/1.1 302 Found
Location: /srv/rdfViewer?url=%2F2013%2F
Content-Length: 0
```

**Comment by bblfish** [comment]
I think this is fixed now Sebastien. The 401 at least.

**Comment by bblfish** [comment]
Je pense que si il y a un probleme c'est plus le 401. Il reste sur Chrome le fait qu'il faut rafraichir la page, mais cela ne se passe pas sur Firefox.

**Comment by slorber** [comment]
Je confirme c'était bien le user agent et le probleme est reglé
