### ISSUE TITLE
subdomain name creation

### ISSUE THREAD

**Issue by bblfish** [read-write-web/rww-play#6]
allow subdomain name creation, such as `cambridge.stample.io`, `virtuelle.stample.io`, etc... . Subdomains protect agains script attacks, so users can be secure with the scripts on their subdomains.

see: http://www.ajax-cross-domain.com/

see for example how http://rww.io/ and look at their source code.

**Comment by bblfish** [comment]
@slorber a dit:

```
je crois que sa conf apache qui permet ca se trouve ici:
https://github.com/deiu/rww.io/blob/a752d40fabca2eb7f191e1bcf14913c36626ac99/conf/worker.conf#L75
docroot web_wild;
web_root = "/srv/www/rww.io";
web_wild = "/srv/www/wildcard.rww.io";
apres je t'avoue que je connais tres tres mal apache
y a de la configuration dns aussi a faire pour que le sous domaine soit branché sur l'ip
```

**Comment by slorber** [comment]
First we should configure the DNS so that the sub domaines redirec to an ip.
You can use the dig unix command to check if it works: dig xxx.stample.io

Then Andrei seems to have Apache configuration to handle that:
https://github.com/deiu/rww.io/blob/master/conf/worker.conf

```
web_wild = "/srv/www/wildcard.rww.io";

...
} else if req.host == "rww.io" or req.host == "rww.io" {
        ......................................
} else {
        openssl.setenv ( "client", "client-cert" );

        docroot web_wild;
        if !phys.exists or req.path =$ "/" {
                rewrite "/index.php";
        }
        docroot web_wild;
        php;

}
```

There's also:
https://github.com/deiu/rww.io/blob/a752d40fabca2eb7f191e1bcf14913c36626ac99/conf/httpd.conf

```
<VirtualHost *:80>
    ServerName cloud.rww.io
    ServerAlias *.rww.io
    Include /home/rww/rww.io/conf/common.conf
    DocumentRoot /home/rww/rww.io/www/wildcard
</VirtualHost>
<VirtualHost *:443>
    ServerName cloud.rww.io
    ServerAlias *.rww.io
    Include /home/rww/rww.io/conf/common.conf
    Include /home/rww/rww.io/conf/ssl.conf
    DocumentRoot /home/rww/rww.io/www/wildcard
</VirtualHost>
```

It seems Andrei retrieve the subdomain name in his code with `$_SERVER['SERVER_NAME']` (variable made available by generic php)
Note that this variable contains the whole domain (ie, stample.rww.io, not just stample)

**Comment by bblfish** [comment]
So from the play Action one needs to get the canonical URL.
There are two ways requests can be made from a client:

``` HTTP
GET https://joe.stample.io/2013/card HTTP/1.1
```

or

``` HTTP
GET /2013/card HTTP/1.1
Host: joe.stample.io:443
```

We need to absolutize the URIs for each Action in ReadWriteWeb, that is
the methods in `ResourceManager` need to take an absolute URI rather than
a String path
`def get(request: PlayRequestHeader, path: String)` => `def get(request: PlayRequestHeader, uri: URI)`
So in both cases above the uri should be `https://joe.stample.io/2013/card`

**Comment by bblfish** [comment]
This explains how to setup subdomains for your localhost server. I have not tried it yet.
http://mikeferrier.com/2011/04/04/setting-up-wildcard-dns-on-localhost-domains-on-osx/

But the simplest - if only useful for one off subdomains - is to edit `/etc/hosts/` and add lines such as

```
127.0.0.1       joe.localhost
127.0.0.1       james.localhost
```
