### ISSUE TITLE
Do not redirect to html viewer if access is forbidden

### ISSUE THREAD

**Issue by slorber** [read-write-web/rww-play#63]
I'm not sure of this

It seems to me that when I go to a created subdomain, like https://sebastien6.localhost:8443/ then we redirect to the RDFViewer url which loads the viewer html and tries to query the ressource in RDF format to display it.

When the ressource is protected by WAC, I guess we should not do that redirect without checking before the user certificate, and we should reply error 401 if he's not allowed (fail fast behavior), because otherwise the viewer will try to query the url and get a 401 later anyway.

**Comment by bblfish** [comment]
yes. Though the JS could also capture the error ( either 401 or a JS connection error ) and show an error message. What do you think @letnotimitateothers  ?

**Comment by letnotimitateothers** [comment]
For now, it seems that the rdflib.js nowOrWhenFetched does not give me http error codes.
I plan to change that.

**Comment by bblfish** [comment]
ok, yes, that's important. 
I think you'll find it is in the graph itself ( or in the no default graph: ie the one with w = undefined ). Tim Berners Lee puts all the http headers in there somewhere, including return codes I think.

**Comment by slorber** [comment]
I have fixed the redirection.

No redirection is done if the resource is forbidden.

But there's will another problem:
https://github.com/stample/rww-play/issues/70

But anyway it will probably be solved by:
https://github.com/stample/rww-play/issues/71
