### ISSUE TITLE
When a resource is forbidden, it is accessible using the viewer!

### ISSUE THREAD

**Issue by slorber** [read-write-web/rww-play#70]
If one uses the link:
https://sebastien1.localhost:8443/
it returns access denied

If one uses the link:
https://sebastien1.localhost:8443/srv/rdfViewer?url=https%3A%2F%2Fsebastien1.localhost%3A8443%2F
It renders the resource.

The RDF viewer should also protect resources

**Comment by slorber** [comment]
Maybe it doesn't worth it to correct this behavior because of https://github.com/stample/rww-play/issues/71
The viewer redirection seems useless for me so the unsecure url will probably not exist in the future

**Comment by bblfish** [comment]
There must be a missing access control test on the requested resource. Should be easy to fix.

**Comment by slorber** [comment]
There's no more viewer so this needs to be closed
See https://github.com/stample/rww-play/issues/71
