### ISSUE TITLE
When rendering a resource using HTML contentType, a redirection is maybe not necessary

### ISSUE THREAD

**Issue by slorber** [read-write-web/rww-play#71]
As we already discussed, using a redirection to the viewer is not such a good idea because when giving a link to a friend, we finally end up sending the link of the viewer + and url queryParam which is not the link of the resource and also break default web reverse proxy caching.

Using a redirect is probably not required and the rendering could be done in the answered html page.

We can bootstrap this page with:
- The graph data to render
- The server mapping for resource rendering (js file per rdf type)
- The call of the application startup function with the graph data

**Comment by bblfish** [comment]
The other solution to the redirect is to include the requested RDF in the HTML. This would be possible using RDFa. But doing that in an automatic way would require some work, and not make for very beautiful or concise HTML - at least not without a lot of careful thought. Furthermore that would require the JS team to see if they can parse the RDFa from the page in which the JS is located, and there may be issues there also. Other solutions are non standard, and a lot less standard than the redirect.

The idea is a good one, but best left for later.

**Comment by slorber** [comment]
@bblfish as I started to work on this issue on friday I continued my work today, trying to do what I describe above: injecting the graph data into the the JS so that there's no need to fetch the graph again and all is available in one request.

Finally I found out by chance that it is not needed and there's a much simpler solution which does not require redirect.

So it's not yet optimized but in the end there's no more redirect

**Comment by bblfish** [comment]
What is the solution without the redirect?

**Comment by slorber** [comment]
Instead of using the url query param of the viewer to know which url is to fetch in RDF format, I simply fetch the document as RDF in the same uri the html document comes from.

Nearly nothing is modified.
I didn't attach the commit so you can find it here:
https://github.com/stample/rww-play/commit/bef8acf666baf189485ac45a00013b9ce7aa8a89

When rendering https://stample.io/2013/ in html, the JS will simply fetch the RDF at https://stample.io/2013/ , the current uri, and it works the same without a redirect

**Comment by bblfish** [comment]
When I tried that first, I found that there was a caching problem. Perhaps that problem was due to something else. But I had the impression the browser would cache some of the requests and then return turtle to the user. See what happens when you click a back button for example.

**Comment by bblfish** [comment]
It seems to work! nice.
