### ISSUE TITLE
com.typesafe.play#sbt-plugin;2.2-TLS: not found

### ISSUE THREAD

**Issue by antonkulaga** [read-write-web/rww-play#79]
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.play#sbt-plugin;2.2-TLS: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by antonkulaga** [comment]
This error fires when I run it with default play 2.2. I see that your build script downloads some other play version, is there a reason for this? Why can't you just use default play 2.2?

**Comment by bblfish** [comment]
Because our version is patched to support TLS client side authentication 
https://github.com/playframework/playframework/pull/1828

**Comment by bblfish** [comment]
So this is a feature, not a bug. :-)
