### ISSUE TITLE
webid certificate CN should not be the WebID

### ISSUE THREAD

**Issue by bblfish** [read-write-web/rww-play#87]
The Common name CN of the created WebID should not be the WebID itself, but something closer to an e-mail address. ![screen shot 2014-02-01 at 16 24 56](https://f.cloud.github.com/assets/124506/2063822/c16af1c6-8cbd-11e3-9ec5-f6290c8d3e85.png)

It may make sense to ask someone for their name so that one can create a username@subdomain.stample.io , or perhaps for the moment just subdomain@stample.io .

**Comment by slorber** [comment]
I think the user should give himself a name to its generated cert don't you think?

**Comment by slorber** [comment]
we can "bootstrap" this name to be subdomain.stample.io

A subdomain can only be created once so this cert name would be unique and easy to identify in the user's browser

**Comment by bblfish** [comment]
yep, that's better thqan what we have now
