### ISSUE TITLE
Use subdomain url for webid in certificate instead of /2013/ url

### ISSUE THREAD

**Issue by slorber** [read-write-web/rww-play#88]
The certificate should not use the `https://stample.io/2013/subdomain/card` webid url but should rather use the `subdomain.stample.io/card` url.

I'm talking about the really used cert field containing the webid attribute, not the common name.

Not sure at all we should keep the 2013 folder (btw we are not in 2013 anymore)

**Comment by bblfish** [comment]
this was fixed. Missing the patch that fixed it. Don't have time to find it.
