### ISSUE TITLE
Crash when opening Subdomain Confirmation email link

### ISSUE THREAD

**Issue by jmvanel** [read-write-web/rww-play#98]
## Here is the message:

Execution exception
[WrongExpectation: expected exactly one node but got 0]
In /home/ubuntu/rww-play/app/utils/subdomain/SubdomainAdminGraphWrapper.scala at line 37.
34  def pointedGraph: PointedGraph[Rdf] = PointedGraph(uri,underlyingGraph)
35
36
37  def email: String = (pointedGraph / stampleAdmin.claimedInbox).as[String].get
38  def password: String = (pointedGraph / stampleAdmin.claimedInboxConfirmationPassword).as[String].get
39
40
41  def emailConfirmed: Boolean = (pointedGraph / stampleAdmin.claimedInboxConfirmed).as[Boolean].getOrElse(false)
42  def subdomainCreated: Option[Rdf#URI] = (pointedGraph / stampleAdmin.subdomainCreated).as[Rdf#URI].toOption

Context:
Chrome on Ubuntu 13.10

**Comment by bblfish** [comment]
Je crois que c'est la même erreur que j'ai eu. Voici une image:
![screen shot 2014-03-10 at 10 28 45](https://f.cloud.github.com/assets/124506/2372178/768c91d4-a836-11e3-9b81-a3282151cd7b.png)

J'ai vérifié: l'addresse mail est bien dans le fichier....

**Comment by slorber** [comment]
Fixed
